apiVersion: v1
kind: PersistentVolumeClaim
metadata:
  name: superspark-data
  namespace: superspark
spec:
  accessModes: ["ReadWriteOnce"]
  resources:
    requests:
      storage: 20Gi
---
apiVersion: v1
kind: PersistentVolumeClaim
metadata:
  name: superspark-logs
  namespace: superspark
spec:
  accessModes: ["ReadWriteOnce"]
  resources:
    requests:
      storage: 10Gi
