apiVersion: v1
kind: ServiceAccount
metadata:
  name: spark
  namespace: superspark
---
apiVersion: rbac.authorization.k8s.io/v1
kind: Role
metadata:
  name: spark-role
  namespace: superspark
rules:
  - apiGroups: [""]
    resources: ["pods", "services", "configmaps", "persistentvolumeclaims"]
    verbs: ["*"]
  - apiGroups: [""]
    resources: ["pods/log"]
    verbs: ["get", "list"]
---
apiVersion: rbac.authorization.k8s.io/v1
kind: RoleBinding
metadata:
  name: spark-role-binding
  namespace: superspark
subjects:
  - kind: ServiceAccount
    name: spark
    namespace: superspark
roleRef:
  kind: Role
  name: spark-role
  apiGroup: rbac.authorization.k8s.io
